#!/bin/bash

. config

# создать скрипт создающий каталоги
if [ ! -f "${out_dir}/mkd" ]
then
  jq -jr --arg out_dir_pls "$out_dir_pls" '
    .data.list[] | .country as $DIR 
    | ("mkdir -p ", "\"", $out_dir_pls, "/", $DIR, "\"\n")' "${out_placeJson}" | sort | uniq > "${out_dir}/mkd"
fi

# и запустить  его
bash "${out_dir}/mkd"

# создать скрипт скачивающий и раскидывающий по папкам page.json
if [ ! -f "${out_dir}/mkp" ]
then
  jq -jr --arg out_dir_pls "${out_dir_pls}" '
    .data.list[] | .country as $DIR | .id as $ID
    | "echo $((C--)) ", $ID, " ; curl -s \"https://radio.garden/api/ara/content/page/", $ID, "/channels\" | jq . > ",
          "\"", $out_dir_pls, "/", $DIR, "/", $ID, ".json", "\"", "\n"' "${out_placeJson}" > "${out_dir}/mkp_"

  echo "C=$(wc -l < ${out_dir}/mkp_)" > "${out_dir}/mkp"
  cat "${out_dir}/mkp_" >> "${out_dir}/mkp"
  rm "${out_dir}/mkp_"
fi

# и запустить  его

bash "${out_dir}/mkp"


exit 0