#!/bin/bash

set -e

. config

echo "#EXTM3U" > "${out_dir}/Radio Garden.m3u8"

IFS=$'\n'
for _d in $(find "${out_dir_pls}/" -mindepth 1 -type d)
do

    all_pls="${out_dir_pls}/$(basename ${_d}) - All Stations.m3u8"
    echo "#EXTM3U" > "${all_pls}"

    for _f in $(find "${_d}" -type f -name '*.m3u8')
    do
        echo -e "\n## === $(basename ${_f}) ===" | tee -a "${out_dir}/Radio Garden.m3u8" >> "${all_pls}"
        tail -n +4 "${_f}" | tee -a "${out_dir}/Radio Garden.m3u8" >> "${all_pls}"
    done
done




